Repository request-yo-racks/web, pull requests merged in 2018-03, with the labels that each got.

#31 Add CircleCI support
  .circleci/config.yml
  .github/CONTRIBUTING.rst
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  Makefile
  src/ryr-location.html
  src/ryr-specify-coordinates.html
  wct.conf.json
Labels: size/S, status/approved

#34 Style guide
  astrum-config.json
  public/pattern-library/LICENSE.txt
  public/pattern-library/app/css/styles.css
  public/pattern-library/app/css/styles.min.css
  public/pattern-library/app/js/main.js
  public/pattern-library/app/js/main.min.js
  public/pattern-library/components/.gitkeep
  public/pattern-library/components/Branding/Color-palette/description.md
  public/pattern-library/components/Branding/Color-palette/markup.html
  public/pattern-library/components/Branding/description.md
  public/pattern-library/components/Buttons/default/description.md
  public/pattern-library/components/Buttons/default/markup.html
  public/pattern-library/components/Buttons/description.md
  public/pattern-library/components/Navigation/Primary/description.md
  public/pattern-library/components/Navigation/Primary/markup.html
  public/pattern-library/components/Navigation/description.md
  public/pattern-library/data.json
  public/pattern-library/index.html
  public/pattern-library/pages/.gitkeep
  public/pattern-library/pages/intro.md
  public/pattern-library/styles/styles.css
Labels: requires changes, size/XXL, status/approved

#28 Float clipboard to the right
  src/my-view1.html
Labels: size/XS, status/requires changes

#41 Update Makefile
  .circleci/config.yml
  Makefile
  README.rst
  tools/bootstrap-npm.sh
  tools/bootstrap-osx.sh
Labels: size/XS

#38 Fix component group names
  images/ryr_logo_favicon.png
  public/pattern-library/components/Navigation/Primary/markup.html
  public/pattern-library/components/input/description.md
  public/pattern-library/components/input/text/description.md
  public/pattern-library/components/input/text/markup.html
  public/pattern-library/components/typography/description.md
  public/pattern-library/components/typography/headers/description.md
  public/pattern-library/components/typography/headers/markup.html
  public/pattern-library/components/typography/text/description.md
  public/pattern-library/components/typography/text/markup.html
  public/pattern-library/data.json
  public/pattern-library/ryr_logo.png
  public/pattern-library/styles/styles.css
Labels: size/S, status/help wanted, status/requires changes

#43 Add .editorconfig file
  .editorconfig
Labels: size/XS

#45 Uses upstream Selenium images to run WCT
  .circleci/config.yml
Labels: size/XS

#39 Change the layout
  .circleci/config.yml
  .gitignore
  bower.json
  images/bikes-on-rack.png
  images/carousel/bikehere-r.png
  images/ryr_logo.png
  images/ryr_logo_text.png
  index.html
  src/my-app.html
  src/my-view1.html
  src/ryr-email-templatizer.html
  src/ryr-location.html
  src/ryr-preview.html
  src/ryr-suggestion-list.html
  src/shared-styles.html
  test/my-view1.html
  wct.conf.json
Labels: size/L

#54 Change the text color of the suggestion list.
  .github/PULL_REQUEST_TEMPLATE.md
  src/ryr-suggestion-list.html
Labels: size/XS

#56 Create target to initialize the configuration
  .circleci/config.yml
  .dockerignore
  Dockerfile
  Makefile
Labels: size/XS

#57 Add logos
  images/logos/ryr_logo_128x128.png
  images/logos/ryr_logo_16x16.png
  images/logos/ryr_logo_22x22.png
  images/logos/ryr_logo_256x256.png
  images/logos/ryr_logo_32x32.png
  images/logos/ryr_logo_48x48.png
  images/logos/ryr_logo_64x64.png
  images/logos/ryr_logo_8x8.png
  images/logos/ryr_logo_text_128x128.png
  images/logos/ryr_logo_text_16x16.png
  images/logos/ryr_logo_text_22x22.png
  images/logos/ryr_logo_text_256x256.png
  images/logos/ryr_logo_text_32x32.png
  images/logos/ryr_logo_text_48x48.png
  images/logos/ryr_logo_text_64x64.png
  images/logos/ryr_logo_text_8x8.png
Labels: size/XS

#44 Clean up ryr-location.html and add unit tests
  src/my-view1.html
  src/ryr-location.html
  test/index.html
  test/mocks/google-map-marker-mock.html
  test/mocks/google-map-mock.html
  test/mocks/paper-input-mock.html
  test/ryr-location.html
Labels: size/M, status/requires changes

#48 Distinguish env differences in client
  .circleci/config.yml
  package.json
  src/my-app.html
  src/ryr-location.html
  src/ryr-suggestion-list.html
  tools/config-js.sh
Labels: size/XS

#60 Clean up the dependencies
  .github/ISSUE_TEMPLATE.md
  Makefile
  README.md
  __README.rst
  bower.json
  src/my-view1.html
  src/ryr-location.html
Labels: size/S
