Repository request-yo-racks/web, pull requests merged in 2018-07, with the labels that each got.

#124 Rename the application
  images/logos/ryr_logo-192x192.png
  images/logos/ryr_logo-512x512.png
  index.html
  manifest.json
Labels: size/XS

#115 Update logos
  images/ryr_logo.png
  images/ryr_logo_favicon.png
Labels: size/XS, status/requires changes

#126 Fix favicon issue inside RYR app.
  images/logos/favicon.ico
  index.html
  manifest.json
Labels: size/XS

#127 Issues/102/tagline update
  src/my-view1.html
Labels: size/XS

#130 Update header image
  images/header-image.jpg
  src/my-view1.html
Labels: size/XS

#128 Issues/104/caution what to do next
  src/my-view1.html
Labels: size/XS

#132 Update the warning box
  src/my-view1.html
Labels: kind/design, size/XS

#131 How-It-Works
  images/how-it-works.png
Labels: kind/design, kind/docs, size/XS

#133 Update section colors, icons and font sizes
  src/my-view1.html
  src/shared-styles.html
Labels: size/S

#134 Make some adjustments to the main page
  src/my-view1.html
Labels: size/XS
