Repository request-yo-racks/web, pull requests merged in 2018-11, with the labels that each got.

#144 Clean up the index page
  pages/index.js
  tests/index.test.js
Labels: size/XS

#145 Add support for Font Awesome
  package-lock.json
  package.json
  pages/index.js
Labels: size/XXL

#146 Create a footer component
  components/ryr-footer.js
  components/service-worker.js
  pages/_app.js
  pages/index.js
Labels: size/XS

#153 Add static files
  static/favicon.ico
  static/images/bike-rack-dark.png
  static/images/how-it-works.png
  static/images/logos/ryr_logo-192x192.png
  static/images/logos/ryr_logo-256x256.png
  static/images/logos/ryr_logo-512x512.png
  static/images/logos/ryr_logo-64x64.png
  static/images/optipng.png
  static/manifest.json
  static/manifest/icon-192x192.png
  static/manifest/icon-512x512.png
  static/manifest/icon.png
Labels: size/XS

#155 Fix mergify configuration
  .mergify.yml
Labels: size/XS

#154 Adjust package.json for windows
  package-lock.json
  package.json
Labels: size/XS

#157 Add how-it-works component
  .mergify.yml
  components/ryr-how-it-works.js
  package-lock.json
  pages/_document.js
  pages/index.js
  server.js
Labels: size/S

#159 Add banner picture
  components/ryr-footer.js
  components/ryr-how-it-works.js
  pages/index.js
Labels: size/XS

#161 Create a connector component
  components/ryr-section-connector.js
  pages/index.js
Labels: size/XS

#165 Implement MapBox-GL map
  .circleci/config.yml
  .gitignore
  .mergify.yml
  components/ryr-location-selector.js
  components/ryr-popup-item.js
  components/ryr-popup.js
  next.config.js
  package-lock.json
  package.json
  pages/index.js
  server.js
Labels: size/L
