Repository request-yo-racks/web, pull requests merged in 2018-04, with the labels that each got.

#65 Style "Get started"
  src/my-app.html
  src/my-view1.html
  src/ryr-location.html
  src/ryr-preview.html
  src/shared-styles.html
Labels: kind/design, size/M

#64 Added color style for preview element.
  src/my-view1.html
  src/ryr-preview.html
Labels: kind/design, size/XS, status/requires changes

#68 Write email instructions
  src/my-view1.html
Labels: size/XS

#72 Fix docker image build
  .gitignore
  Dockerfile
  Dockerfile.dev
  __README.rst
  src/config.js
  src/ryr-suggestion-list.html
  tools/config-js.sh
Labels: size/S

#69 Change Footer Icons and Alignment
  bower.json
  images/icons/FB-icon.png
  images/icons/GitHub-Mark-Light-32px.png
  images/icons/GitHub-Mark-Light-64px.png
  images/icons/GitHub_Logo.png
  images/icons/GitHub_Logo_White.png
  images/icons/Twitter_Social_Icon_Rounded_Square_Color.png
  images/icons/Twitter_Social_Icon_Rounded_Square_White.png
  src/my-app.html
  src/shared-styles.html
Labels: size/S
