Repository request-yo-racks/web, pull requests merged in 2019-01, with the labels that each got.

#177 Use emotion for index.js
  package-lock.json
  package.json
  pages/index.js
Labels: size/M

#178 Use emotion to style How-It-Works
  components/ryr-how-it-works.js
Labels: size/XS

#179 Use emotion to style PopUpItem
  components/ryr-how-it-works.js
  components/ryr-popup-item.js
  pages/index.js
Labels: size/XS

#180 Make the UI responsive
  components/ryr-how-it-works.js
  package-lock.json
  package.json
  pages/index.js
Labels: size/XS

#183 Add copy-to-clipboard button
  components/ryr-email.js
  components/ryr-how-it-works.js
  components/ryr-preview.js
  package-lock.json
  package.json
  pages/index.js
Labels: size/S

#163 Create instructions component
  components/ryr-instructions.js
  pages/index.js
Labels: size/S
